-- ATBM-CQ-14
-- 21120344 - Nguyen Trong Tri
-- 21120321 - Nguyen Van Sieu
-- 21120565 - Tran Van Thong
-- 21120416 - Vo Quoc Bao
conn sys/123@localhost:1521/xepdb1 as sysdba ; 
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE ;

DROP USER QLDLNB CASCADE;

CREATE USER QLDLNB IDENTIFIED BY ADMIN QUOTA 100M ON USERS;
GRANT ALL PRIVILEGES TO QLDLNB;
ALTER SESSION SET CURRENT_SCHEMA = QLDLNB ; 

-- Xoa cau truc co so du lieu
-- Tao cau truc co so du lieu
-- NHANSU
CREATE TABLE NHANSU (
    MANV NUMBER(10) PRIMARY KEY,
    HOTEN NVARCHAR2(50),
    PHAI NVARCHAR2(10),
    NGSINH DATE,
    PHUCAP NUMBER(10),
    DT VARCHAR2(15),
    VAITRO NVARCHAR2(50),
    MADV NUMBER(4),
    COSO VARCHAR(10)
);

-- SINHVIEN
CREATE TABLE SINHVIEN (
    MASV NUMBER(10) PRIMARY KEY,
    HOTEN NVARCHAR2(50),
    PHAI NVARCHAR2(100),
    NGSINH DATE,
    DCHI NVARCHAR2(100),
    DT VARCHAR2(15),
    MACT VARCHAR(10),
    MANGANH VARCHAR2(10),
    SOTCTL NUMBER(10),
    DTBTL FLOAT,
    COSO VARCHAR2(10)
);

-- DONVI
CREATE TABLE DONVI (
    MADV NUMBER(10) PRIMARY KEY,
    TENDV NVARCHAR2(100),
    TRGDV NUMBER(10)
);

-- HOCPHAN
CREATE TABLE HOCPHAN (
    MAHP NUMBER(10) PRIMARY KEY,
    TENHP NVARCHAR2(100),
    SOTC NUMBER,
    STLT NUMBER(2),
    STTH NUMBER(2),
    SOSVTD NUMBER(3),
    MADV NUMBER(10),
    TRUONGBM NUMBER(10)
);

-- KHMO
CREATE TABLE KHMO (
    MAHP NUMBER(10),
    HK NUMBER,
    NAM NUMBER(4),
    MACT VARCHAR2(10),
    CONSTRAINT PK_KHMO PRIMARY KEY (MAHP, HK, NAM, MACT)
);

-- PHANCONG
CREATE TABLE PHANCONG (
    MAGV NUMBER(10),
    MAHP NUMBER(10),
    HK NUMBER,
    NAM NUMBER(4),
    MACT VARCHAR2(10),
    CONSTRAINT PK_PHANCONG PRIMARY KEY (MAGV, MAHP, HK, NAM, MACT)
);

-- DANGKY
CREATE TABLE DANGKY (
    MASV NUMBER(10),
    MAGV NUMBER(10),
    MAHP NUMBER(10),
    HK NUMBER(10),
    NAM NUMBER(10),
    MACT VARCHAR2(10),
    DIEMTH FLOAT,
    DIEMQT FLOAT,
    DIEMCK FLOAT,
    DIEMTK FLOAT,
    CONSTRAINT PK_DANGKY PRIMARY KEY (MASV, MAGV, MAHP, HK, NAM, MACT)
);


-- -- Rang buoc khoa ngoai
-- -- NHANSU
-- ALTER TABLE NHANSU ADD CONSTRAINT FK_NHANSU_DONVI FOREIGN KEY (MADV) REFERENCES DONVI(MADV);

-- -- DONVI
-- ALTER TABLE DONVI ADD CONSTRAINT FK_DONVI_NHANSU FOREIGN KEY (TRGDV) REFERENCES NHANSU(MANV);

-- -- HOCPHAN
-- ALTER TABLE HOCPHAN ADD CONSTRAINT FK_HOCPHAN_DONVI FOREIGN KEY (MADV) REFERENCES DONVI(MADV);  

-- -- KHMO
-- ALTER TABLE KHMO ADD CONSTRAINT FK_KHMO_HOCPHAN FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP);

-- -- PHANCONG
-- ALTER TABLE PHANCONG ADD (
--     CONSTRAINT FK_PHANCONG_NHANSU FOREIGN KEY (MAGV) REFERENCES NHANSU(MANV),
--     CONSTRAINT FK_PHANCONG_HOCPHAN FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP)
-- );

-- -- DANGKY
-- ALTER TABLE DANGKY ADD (
--     CONSTRAINT FK_DANGKY_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
--     CONSTRAINT FK_DANGKY_NHANSU FOREIGN KEY (MAGV) REFERENCES NHANSU(MANV),
--     CONSTRAINT FK_DANGKY_HOCPHAN FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP)
-- );



-- Chen du lieu vao co so du lieu
--INSERT ALL 
--    INTO NHANSU VALUES ()
--    INTO NHANSU VALUES ()
--    INTO NHANSU VALUES ()
--SELECT * FROM DUAL;





