-- standard audit ;
connect sys/123@localhost:1521/XEPDB1 AS SYSDBA ; 
ALTER SESSION SET CURRENT_SCHEMA = QLDLNB; 
AUDIT TABLE ;
-- VIEW 
AUDIT SELECT, UPDATE, DELETE, INSERT ON UV_NVCB_XEMTTCN BY ACCESS;
AUDIT SELECT, UPDATE, DELETE, INSERT ON UV_NVCB_XEMTT_SV BY ACCESS; 
AUDIT SELECT, UPDATE, DELETE, INSERT ON UV_NVCB_XEMTT_KHMO BY ACCESS; 
AUDIT SELECT, UPDATE, DELETE, INSERT ON UV_NVCB_XEMTT_HOCPHAN BY ACCESS;
AUDIT SELECT, UPDATE, DELETE, INSERT ON UV_NVCB_XEMTT_DV BY ACCESS;


AUDIT SELECT, UPDATE, DELETE, INSERT ON UV_GV_XEMTT_DANGKY BY ACCESS;
AUDIT SELECT, UPDATE, DELETE, INSERT ON  UV_GV_XEMTT_PHANCONG BY ACCESS; 


AUDIT SELECT, UPDATE, DELETE, INSERT ON UV_GIAOVU_XEMTT_SINHVIEN BY ACCESS;
AUDIT SELECT, UPDATE, DELETE, INSERT ON UV_GIAOVU_XEMTT_DONVI BY ACCESS; 
AUDIT SELECT, UPDATE, DELETE, INSERT ON UV_GIAOVU_XEMTT_HOCPHAN BY ACCESS; 
AUDIT SELECT, UPDATE, DELETE, INSERT ON UV_GIAOVU_XEMTT_KHMO BY ACCESS;
AUDIT SELECT, UPDATE, DELETE, INSERT ON UV_GIAOVU_XEMTT_PHANCONG BY ACCESS;

AUDIT SELECT, UPDATE, DELETE, INSERT ON UV_TDV_XEMTT_PHANCONG BY ACCESS;

AUDIT SELECT ON UV_TK_XEMTT_DONVI BY ACCESS;
AUDIT SELECT ON UV_TK_XEMTT_KHMO  BY ACCESS;
AUDIT SELECT ON UV_TK_XEMTT_SINHVIEN BY ACCESS;
AUDIT SELECT ON UV_TK_XEMTT_HOCPHAN BY ACCESS;

AUDIT SELECT ON KHMO BY ACCESS;
AUDIT SELECT ON HOCPHAN BY ACCESS;
AUDIT SELECT ON DANGKY BY ACCESS;
AUDIT SELECT , UPDATE SINHVIEN BY ACCESS;

SELECT * FROM DBA_AUDIT_TRAIL WHERE USERNAME LIKE 'NV%';
